// Package smoketest exercises the full Layer 1 → Layer 2 pipeline without
// any live GitHub API. It proves:
//   - A key generated by signing.NewSigner() can sign a manifest.Manifest.
//   - verify.Verify() returns StatusApproved for a correctly signed manifest.
//   - verify.Verify() returns StatusTampered when payload bytes are flipped.
//   - registry.Lookup() can round-trip a PEM-encoded public key via env vars.
package smoketest

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"testing"

	"github.com/Dev-31/provenance-layer1/manifest"
	"github.com/Dev-31/provenance-layer1/signing"
	"github.com/Dev-31/provenance-layer2/internal/registry"
	"github.com/Dev-31/provenance-layer2/internal/verify"
	"github.com/stretchr/testify/require"
)

const testHeadSHA = "abc123def456abc123def456abc123def456abc1"

// TestEndToEndSignAndVerify proves the full keygen → sign → verify cycle works
// across the Layer 1 / Layer 2 boundary without any live GitHub API.
func TestEndToEndSignAndVerify(t *testing.T) {
	// Step 1: keygen (ephemeral in-memory key).
	signer, err := signing.NewSigner()
	require.NoError(t, err, "NewSigner must not fail")

	// Step 2: build a manifest and sign it.
	m := &manifest.Manifest{
		SchemaVersion: manifest.SchemaVersion,
		Agent:         manifest.AgentInfo{ID: "smoke-agent", Version: "1.0", Provider: "test"},
		Invocation:    manifest.InvocationInfo{TimestampUTC: "2026-04-27T00:00:00Z", WorkingDir: "/tmp"},
		Verification:  manifest.VerificationInfo{TestsRun: true, TestExitCode: 0, DurationMs: 42},
		PR: &manifest.PRInfo{
			Repo:    "owner/repo",
			Number:  1,
			HeadSHA: testHeadSHA,
		},
	}
	payload, err := m.Payload()
	require.NoError(t, err, "Payload() must not fail")

	sig, err := signer.Sign(payload)
	require.NoError(t, err, "Sign() must not fail")
	m.Signature = sig

	data, err := json.Marshal(m)
	require.NoError(t, err, "json.Marshal must not fail")

	// Step 3: verify via Layer 2 — expect APPROVED.
	result := verify.Verify(data, signer.PublicKey(), testHeadSHA)
	require.Equal(t, verify.StatusApproved, result.Status,
		"expected APPROVED, got %s: %s", result.Status, result.Reason)
	require.True(t, result.HeadSHAMatch, "HeadSHAMatch must be true when SHA matches")
	require.NotNil(t, result.Manifest)
	require.Equal(t, "smoke-agent", result.Manifest.Agent.ID)

	// Step 4: tamper detection — flip one byte and expect TAMPERED.
	data[50] ^= 0xFF
	tampered := verify.Verify(data, signer.PublicKey(), testHeadSHA)
	require.Equal(t, verify.StatusTampered, tampered.Status,
		"bit-flipped manifest must return TAMPERED")
}

// TestHeadSHAMismatchIsApprovedWithFlagFalse verifies that a mismatched head SHA
// still returns APPROVED status but sets HeadSHAMatch=false.
func TestHeadSHAMismatchIsApprovedWithFlagFalse(t *testing.T) {
	signer, err := signing.NewSigner()
	require.NoError(t, err)

	m := &manifest.Manifest{
		SchemaVersion: manifest.SchemaVersion,
		Agent:         manifest.AgentInfo{ID: "sha-mismatch-agent", Version: "1.0", Provider: "test"},
		Invocation:    manifest.InvocationInfo{TimestampUTC: "2026-04-27T00:00:00Z", WorkingDir: "/tmp"},
		Verification:  manifest.VerificationInfo{TestsRun: false},
		PR:            &manifest.PRInfo{Repo: "owner/repo", Number: 2, HeadSHA: "aaaaaa"},
	}
	payload, err := m.Payload()
	require.NoError(t, err)
	sig, err := signer.Sign(payload)
	require.NoError(t, err)
	m.Signature = sig

	data, err := json.Marshal(m)
	require.NoError(t, err)

	// Provide a different actualHeadSHA — signature is still valid, but SHA does not match.
	result := verify.Verify(data, signer.PublicKey(), "bbbbbb")
	require.Equal(t, verify.StatusApproved, result.Status, "signature-valid result must still be APPROVED")
	require.False(t, result.HeadSHAMatch, "HeadSHAMatch must be false when SHAs differ")
}

// TestVerifyBadJSONReturnsTampered confirms that non-JSON input returns TAMPERED.
func TestVerifyBadJSONReturnsTampered(t *testing.T) {
	result := verify.Verify([]byte("not valid json"), nil, "")
	require.Equal(t, verify.StatusTampered, result.Status)
}

// TestVerifyMissingSignatureReturnsUnverified confirms that a JSON manifest
// without a signature field returns UNVERIFIED.
func TestVerifyMissingSignatureReturnsUnverified(t *testing.T) {
	m := &manifest.Manifest{
		SchemaVersion: manifest.SchemaVersion,
		Agent:         manifest.AgentInfo{ID: "no-sig-agent", Version: "1.0", Provider: "test"},
		Invocation:    manifest.InvocationInfo{TimestampUTC: "2026-04-27T00:00:00Z", WorkingDir: "/tmp"},
		Verification:  manifest.VerificationInfo{},
	}
	// Do NOT set m.Signature.
	data, err := json.Marshal(m)
	require.NoError(t, err)

	result := verify.Verify(data, nil, "")
	require.Equal(t, verify.StatusUnverified, result.Status)
}

// TestPublicKeyRegistryRoundTrip confirms a P-256 public key can be stored
// via env var and retrieved by registry.Lookup with no loss of information.
func TestPublicKeyRegistryRoundTrip(t *testing.T) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	require.NoError(t, err)

	der, err := x509.MarshalPKIXPublicKey(&key.PublicKey)
	require.NoError(t, err)
	pemStr := string(pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: der}))

	// t.Setenv restores the original value automatically after the test.
	t.Setenv("PROVENANCE_PUBKEY_SMOKE_AGENT", pemStr)

	pub, err := registry.Lookup("smoke-agent")
	require.NoError(t, err, "registry.Lookup must succeed when env var is set")
	require.True(t, key.PublicKey.Equal(pub), "round-tripped key must equal original")
}
